"use strict";

var config = {
    formEditableValues : ["fraction", "fractionCount", "recoveryHalftime", "alphabeta", "dayOfWeek","fractionProceed","prolif"],
    formReadonlyValues : ["offDays","treatmentDays","totalDose","EQD2", "BED", "EQD2prolif", "factTreatmentDays", "factOffDays"],
    weekDayNames : ["пн","вт","ср","чт","пт","сб","вс"],
    maxFractions : 70,
    maxFractionsPerDay: 3,
    emptyDay : "0",
    offDay: "1",
    onDay: "2",
    defaultMultifractionPeriod: [null, null, 6, 3],
    
    labels: {},
    labels_en: {
        main_title : "LQ-model for Medical Physicists and Radiation Oncologists",
        fraction_lbl: "Dose per fraction, Gy",
        fraction_count_lbl:"Fractions",
        day_of_week_lbl:"Start of treatment",
        fraction_proceed_lbl: "Fractions proceed",
        alphabeta_lbl: "α/β ratio <span class='link' data-toggle='modal' data-target='#fract-sensitivity'>(info)</span>",
        recovery_halftime_lbl: "Recovery halftime, <i>T<sub>1/2</sub></i>, hours <span class='link' data-toggle='modal' data-target='#rec-halftime'>(info)</span>",
        prolif_lbl: "Use <i>D<sub>prolif</sub></i> <span class='link' data-toggle='modal' data-target='#d-prolif'>(info)</span>",
        prolif_lbl_hint: "Proliferation can be used if overall treatment time exceed 21 days",
        treatment_days_lbl: "Overall treatment days <i>T</i>",
        off_days_lbl: "Treatment gap days",
        total_dose_lbl: "Total dose <i>D</i>, Gy",
        // received_dose_lbl: "Received dose, Gy",
        // remaining_dose_lbl: "Remaining dose, Gy",
        EQD2_lbl:"Equivalent dose <i>EQD<sub>2</sub></i>, Gy",
        EQD2prolif_lbl: "Equivalent dose owing to proliferation, Gy",
        BED_lbl: "Biological Effective Dose (BED), Gy",
        schedule_lbl: "Treatment schedule",
        add_week_lbl: "Add a week",
        time_interval_header: "Select time interval between fractions",
        time_interval_col1: "Interval between fractions (hours)",
        time_interval_col2: "Dose per fraction, Gy",
        LQ_alert_lbl: "LQ model is justified for doses not exceeding 6-8 Gy!",
        factTreatmentDays_lbl: "Factual treatment days",
        factOffDays_lbl:"Factual gap days",

        weekDayNames: ["Mo","Tu","We","Th","Fr","Sa","Su"],
        gray: "Gy",
        hour: "h",
    },
    labels_ru: {
        main_title : "Линейно-квадратичная модель для медицинских физиков и радиационных онкологов",
        fraction_lbl: "Разовая очаговая доза, Гр",
        fraction_count_lbl:"Кол-во рабочих дней (фракций)",
        day_of_week_lbl:"День недели начала лечения",
        fraction_proceed_lbl: "Прошло фракций",
        alphabeta_lbl: "Коэффициент α/β <span class='link' data-toggle='modal' data-target='#fract-sensitivity'>(инфо)</span>",
        recovery_halftime_lbl: "Время полувосстановления <i>T<sub>1/2</sub></i>, часы <span class='link' data-toggle='modal' data-target='#rec-halftime'>(инфо)</span>",
        prolif_lbl: "Учитывать пролиферацию <i>D<sub>prolif</sub></i> <span class='link' data-toggle='modal' data-target='#d-prolif'>(инфо)</span>",
        prolif_lbl_hint: "Учет пролиферации возможен при длительности лечения от 21 дня",
        treatment_days_lbl: "Кол-во дней лечения, <i>T</i>",
        off_days_lbl: "Кол-во выходных",
        total_dose_lbl: "Суммарная очаговая доза <i>D</i>, Гр",
        // received_dose_lbl: "Полученная доза, Гр",
        // remaining_dose_lbl: "Оставшаяся доза, Гр",
        EQD2_lbl: "Эквивалентная доза <i>EQD<sub>2</sub></i>, Гр",
        EQD2prolif_lbl: "Эквивалентная доза c учетом пропущенных дней, Гр",
        BED_lbl: "Биологически эффективная доза (BED), Гр",
        schedule_lbl: "Расписание лечения",
        add_week_lbl: "Добавить неделю",
        time_interval_header: "Выберите интервал между фракциями",
        time_interval_col1: "Интервал между фракциями, ч",
        time_interval_col2: "Разовая доза, Гр",
        LQ_alert_lbl: "Использование ЛК-модели обосновано для доз не превышающих 6-8 Гр !",
        factTreatmentDays_lbl: "Фактическое кол-во дней лечения",
        factOffDays_lbl:"Фактическое кол-во пропущенных дней",

        weekDayNames: ["пн","вт","ср","чт","пт","сб","вс"],
        gray: "Гр",
        hour: "ч",
    }
 }
